DROP VIEW BUYERS_VIEW CASCADE;
DROP VIEW PRODUCTS_VIEW CASCADE;
DROP VIEW PRODUCTS_SOLD_VIEW CASCADE;
DROP VIEW REPORT_VIEW CASCADE;


CREATE VIEW BUYERS_VIEW AS 
SELECT USERS.*, BUYERS.BUYER_ID
FROM BUYERS
	INNER JOIN USERS ON (BUYERS.BUYER_ID = USERS.ID)
;

CREATE VIEW PRODUCTS_VIEW AS 
SELECT PRODUCTS.NAME, INVENTORY.PRICE, INVENTORY.ID
FROM INVENTORY
	INNER JOIN PRODUCTS ON (INVENTORY.PRODUCT_ID = PRODUCTS.ID)
;

CREATE VIEW PRODUCTS_SOLD_VIEW AS 
SELECT PRODUCTS_VIEW.NAME, PRODUCTS_VIEW.PRICE, PRODUCTS_VIEW.ID, CARTS.SOLD_ORDER_ID
FROM PRODUCTS_VIEW
	INNER JOIN CARTS ON (PRODUCTS_VIEW.ID = CARTS.INVENTORY_ID AND CARTS.SOLD_ORDER_ID>0)
;

CREATE VIEW REPORT_VIEW AS
SELECT ORDERS.ID AS ORDER_ID, ORDERS.TIMESTAMP, PRODUCTS_SOLD_VIEW.NAME AS PRODUCT_NAME, PRODUCTS_SOLD_VIEW.PRICE, ORDERS.ORDER_TOTAL, BUYERS_VIEW.NAME AS BUYERS_NAME, BUYERS_VIEW.EMAIL AS BUYERS_EMAIL 
FROM ORDERS
	INNER JOIN BUYERS_VIEW ON (BUYERS_VIEW.BUYER_ID = ORDERS.BUYER_ID)
	INNER JOIN PRODUCTS_SOLD_VIEW ON (ORDERS.ID = PRODUCTS_SOLD_VIEW.SOLD_ORDER_ID)
WHERE current_date - 30 < ORDERS.TIMESTAMP
;

SELECT * FROM REPORT_VIEW;
