


SELECT ORDERS.ID, ORDERS.ORDER_TOTAL, CARTS.DISCOUNT_OFFERED, ORDERS.TIMESTAMP, DISCOUNTS.HASH_CODE AS DISCOUNT_CODE, PAYMENTGATEWAYS.NAME AS PAYMENT_GATEWAY, ORDERS.PAYMENT_STATUS
FROM ORDERS
	INNER JOIN DISCOUNTS
		ON ORDERS.DISCOUNT_ID = DISCOUNTS.ID
	INNER JOIN PAYMENTGATEWAYS
		ON ORDERS.PAYMENT_ID = PAYMENTGATEWAYS.ID
	INNER JOIN CARTS
		ON CARTS.SOLD_ORDER_ID = ORDERS.ID;
;
