/*
 - AT ANY GIVEN TIME, DB KNOWS WHICH BUYER BOUGHT WHICH VARIANT OF WHICH PRODUCT FROM WHICH SELLER?
 - AUTO CALCULATES DISCOUNTS IN PERCENTAGES.
 - A BUYER CAN MAKE MULTIPLE PURCHASES OF THE SAME PRODUCT (SAME VARIANT) IN THE SAME ORDER (OR DIFFERENT ORDER)
 - NORMALIZED TO THE POINT WHERE IT HURTS TO READ!
*/


drop schema public cascade;
create schema public;

CREATE TABLE USERS(
   ID SERIAL PRIMARY KEY NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   ADDRESS VARCHAR(50)
);

CREATE TABLE BUYERS(
   BUYER_ID INT PRIMARY KEY NOT NULL REFERENCES USERS(ID)
);

CREATE TABLE SELLERS(
   SELLER_ID INT PRIMARY KEY NOT NULL REFERENCES USERS(ID)
);

CREATE TABLE PRODUCTS(
   ID SERIAL PRIMARY KEY NOT NULL,
   NAME VARCHAR(50),
   DESCRIPTION VARCHAR(500)
);

CREATE TABLE COLORS(
   ID SERIAL PRIMARY KEY NOT NULL,
   HEX_VALUE VARCHAR(50) NOT NULL
);

CREATE TABLE INVENTORY(
   ID SERIAL PRIMARY KEY NOT NULL,
   PRODUCT_ID INT NOT NULL REFERENCES PRODUCTS(ID),
   PRICE INT NOT NULL,
   QUANTITY INT NOT NULL,
   COLOR_ID INT REFERENCES COLORS(ID),
   SELLER_ID INT REFERENCES SELLERS(SELLER_ID)
);

CREATE TABLE CARTS(
   ID SERIAL PRIMARY KEY NOT NULL,
   INVENTORY_ID INT,
   BUYER_ID INT,
	ORIGINAL_PRICE INT DEFAULT 0,
	DISCOUNT_OFFERED INT DEFAULT 0,
	SOLD_ORDER_ID INT DEFAULT 0 -- HOLDS ORDER_ID. 0 IMPLIES NOT SOLD.
);

CREATE TABLE PAYMENTGATEWAYS(
   ID SERIAL PRIMARY KEY NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE DISCOUNTS(
   ID SERIAL PRIMARY KEY NOT NULL,
   HASH_CODE VARCHAR(20),
   PERCENT_DISCOUNT INT
);

CREATE TABLE ORDERS(
   ID SERIAL PRIMARY KEY NOT NULL,
   BUYER_ID INT REFERENCES BUYERS(BUYER_ID),
   ORDER_TOTAL INT,
   DISCOUNT_ID INT DEFAULT 1, -- ID OF 1 EQUALS 0% DISCOUNT. ACTUAL DISCOUNT_IDs START FROM 2.
   TIMESTAMP DATE,
   PAYMENT_STATUS INT DEFAULT 0, -- ACTS LIKE BOOLEAN. 0 IS SOLD, 1 IS NOT SOLD.
   PAYMENT_ID INT DEFAULT 0 -- WHICH PAYMENT GATEWAY (ID)? DEFAULT 0 IS NOT PAID. 
);

CREATE TABLE TRANSACTIONS(
   ID SERIAL PRIMARY KEY NOT NULL,
   BUYER_ID INT REFERENCES BUYERS(BUYER_ID),
   SELLER_ID INT REFERENCES SELLERS(SELLER_ID),
   INVENTORY_ID INT REFERENCES INVENTORY(ID),
   DISCOUNT_ID INT REFERENCES DISCOUNTS(ID),
   PAYMENT_ID INT REFERENCES PAYMENTGATEWAYS(ID),
   TIMESTAMP DATE 
);

