drop schema public cascade;
create schema public;

CREATE TABLE USERS(
   ID SERIAL PRIMARY KEY NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   ADDRESS VARCHAR(50)
);

CREATE TABLE BUYERS(
   BUYER_ID INT PRIMARY KEY NOT NULL REFERENCES USERS(ID)
);

CREATE TABLE SELLERS(
   SELLER_ID INT PRIMARY KEY NOT NULL REFERENCES USERS(ID)
);

CREATE TABLE PRODUCTS(
   ID SERIAL PRIMARY KEY NOT NULL,
   NAME VARCHAR(50),
   DESCRIPTION VARCHAR(500)
);

CREATE TABLE COLORS(
   ID SERIAL PRIMARY KEY NOT NULL,
   HEX_VALUE VARCHAR(50) NOT NULL
);

CREATE TABLE INVENTORY(
   ID SERIAL PRIMARY KEY NOT NULL,
   PRODUCT_ID INT NOT NULL REFERENCES PRODUCTS(ID),
   PRICE INT NOT NULL,
   QUANTITY INT NOT NULL,
   COLOR_ID INT REFERENCES COLORS(ID),
   SELLER_ID INT REFERENCES SELLERS(SELLER_ID)
);

CREATE TABLE PAYMENTGATEWAYS(
   ID SERIAL PRIMARY KEY NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE DISCOUNTS(
   ID SERIAL PRIMARY KEY NOT NULL,
   HASH_CODE VARCHAR(20),
   PERCENT_DISCOUNT INT
);

CREATE TABLE TRANSACTIONS(
   ID SERIAL PRIMARY KEY NOT NULL,
   BUYER_ID INT REFERENCES BUYERS(BUYER_ID),
   SELLER_ID INT REFERENCES SELLERS(SELLER_ID),
   INVENTORY_ID INT REFERENCES INVENTORY(ID),
   DISCOUNT_ID INT REFERENCES DISCOUNTS(ID),
   PAYMENT_ID INT REFERENCES PAYMENTGATEWAYS(ID),
   TIMESTAMP DATE 
);
