UPDATE ORDERS SET PAYMENT_STATUS=1, PAYMENT_ID=1 WHERE BUYER_ID=2;

UPDATE ORDERS SET PAYMENT_STATUS=1, PAYMENT_ID=1 WHERE BUYER_ID=3;

UPDATE ORDERS SET PAYMENT_STATUS=1, PAYMENT_ID=2, DISCOUNT_ID=2 WHERE BUYER_ID=6;

